// Generated by schema/generate_types.py. Do not edit.

export interface CameraSpec {
  readonly w: number;
  readonly h: number;
  readonly hfov_deg: number;
}

export interface HelloMessage {
  readonly type: "hello";
  readonly fps: number;
  readonly camera: CameraSpec;
}

export interface GazeMessage {
  readonly type: "gaze";
  readonly t: number;
  readonly present: boolean;
  readonly yaw_deg: number;
  readonly pitch_deg: number;
  readonly az: number;
  readonly el: number;
  readonly conf: number;
}

export interface VadMessage {
  readonly type: "vad";
  readonly t: number;
  readonly event: "start";
}

export interface TtsDoneMessage {
  readonly type: "tts_done";
  readonly t: number;
}

export interface ErrorMessage {
  readonly type: "error";
  readonly where: string;
  readonly detail: string;
}

export interface JointsState {
  readonly base_yaw: number;
  readonly shoulder_pitch: number;
  readonly elbow_pitch: number;
  readonly neck_yaw: number;
  readonly head_pitch: number;
}

export interface LightState {
  readonly intensity: number;
  readonly color_k: number;
  readonly pattern: "steady" | "pulse" | "flicker" | "blink";
  readonly bloom: number;
}

export interface AudioState {
  readonly speaking: boolean;
  readonly arousal: number;
}

export interface ClampCounts {
  readonly vel: number;
  readonly limit: number;
}

export interface TelemetryGaze {
  readonly present: boolean;
  readonly yaw_deg: number;
  readonly pitch_deg: number;
}

export interface TelemetryState {
  readonly state: "BOOT" | "DORMANT" | "NOTICING" | "ENGAGED" | "LISTENING" | "THINKING" | "SPEAKING" | "INSPECTING" | "ACTING" | "DISENGAGING";
  readonly plan_depth: number;
  readonly memory_count: number;
  readonly last_latency_ms: number;
  readonly clamps: ClampCounts;
  readonly gaze: TelemetryGaze;
}

export interface BodyStateMessage {
  readonly type: "body_state";
  readonly t: number;
  readonly seq: number;
  readonly joints: JointsState;
  readonly light: LightState;
  readonly audio: AudioState;
  readonly telemetry: TelemetryState;
}

export interface CueMessage {
  readonly type: "cue";
  readonly sfx: "chirp_up" | "chirp_found" | "boing" | "whirr_short" | "hmm" | "blip_sad" | "fanfare_small" | "click";
}

export interface CaptureFrameMessage {
  readonly type: "capture_frame";
  readonly req_id: string;
}

export interface SpeakBeginMessage {
  readonly type: "speak_begin";
  readonly envelope_hz: number;
}

export interface SpeakEndMessage {
  readonly type: "speak_end";
}

export type TextMessage = HelloMessage | GazeMessage | VadMessage | TtsDoneMessage | ErrorMessage | BodyStateMessage | CueMessage | CaptureFrameMessage | SpeakBeginMessage | SpeakEndMessage;

export type BrowserToCoreMessage = HelloMessage | GazeMessage | VadMessage | TtsDoneMessage | ErrorMessage;

export type CoreToBrowserMessage = BodyStateMessage | CueMessage | CaptureFrameMessage | SpeakBeginMessage | SpeakEndMessage;

export const BinaryPrefix = {
  utterance_pcm: 0x01,
  capture_jpeg: 0x02,
  tts_pcm: 0x03,
} as const;

export type BinaryFrameName = keyof typeof BinaryPrefix;
export type BinaryPrefixValue = (typeof BinaryPrefix)[BinaryFrameName];
