#!/usr/bin/env python3
"""Generate renderer TypeScript protocol types from the JSON Schema."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SCHEMA = REPO_ROOT / "schema" / "messages.schema.json"
DEFAULT_OUTPUT = REPO_ROOT / "renderer" / "src" / "protocol" / "types.ts"


def _ref_name(ref: str) -> str:
    prefix = "#/$defs/"
    if not ref.startswith(prefix):
        raise ValueError(f"unsupported reference: {ref}")
    return ref.removeprefix(prefix)


def _literal(value: Any) -> str:
    if value is None:
        return "null"
    if value is True:
        return "true"
    if value is False:
        return "false"
    return json.dumps(value, ensure_ascii=False)


def _typescript_type(node: dict[str, Any]) -> str:
    if "$ref" in node:
        return _ref_name(node["$ref"])
    if "const" in node:
        return _literal(node["const"])
    if "enum" in node:
        return " | ".join(_literal(value) for value in node["enum"])
    if "oneOf" in node:
        return " | ".join(_typescript_type(part) for part in node["oneOf"])

    node_type = node.get("type")
    if isinstance(node_type, list):
        return " | ".join(_typescript_type({**node, "type": part}) for part in node_type)
    if node_type in ("integer", "number"):
        return "number"
    if node_type == "string":
        return "string"
    if node_type == "boolean":
        return "boolean"
    if node_type == "null":
        return "null"
    if node_type == "array":
        return f"ReadonlyArray<{_typescript_type(node['items'])}>"
    if node_type == "object":
        properties = node.get("properties", {})
        required = set(node.get("required", []))
        members = [
            f"readonly {name}{'' if name in required else '?'}: {_typescript_type(prop)};"
            for name, prop in properties.items()
        ]
        return "{ " + " ".join(members) + " }"
    raise ValueError(f"unsupported schema node: {node}")


def _definition(name: str, node: dict[str, Any]) -> list[str]:
    if node.get("type") != "object" or "properties" not in node:
        return [f"export type {name} = {_typescript_type(node)};", ""]

    required = set(node.get("required", []))
    lines = [f"export interface {name} {{"]
    for property_name, property_schema in node["properties"].items():
        optional = "" if property_name in required else "?"
        lines.append(
            f"  readonly {property_name}{optional}: {_typescript_type(property_schema)};"
        )
    lines.extend(["}", ""])
    return lines


def generate(schema_path: Path = DEFAULT_SCHEMA) -> str:
    schema = json.loads(schema_path.read_text(encoding="utf-8"))
    lines = [
        "// Generated by schema/generate_types.py. Do not edit.",
        "",
    ]

    for name, definition in schema["$defs"].items():
        lines.extend(_definition(name, definition))

    root_members = " | ".join(_typescript_type(item) for item in schema["oneOf"])
    lines.extend([f"export type TextMessage = {root_members};", ""])

    directions = schema["x-message-directions"]
    for direction, members in directions.items():
        type_name = "".join(part.capitalize() for part in direction.split("-")) + "Message"
        lines.extend([f"export type {type_name} = {' | '.join(members)};", ""])

    lines.append("export const BinaryPrefix = {")
    for frame in schema["x-binary-frames"]:
        lines.append(f"  {frame['name']}: {frame['hex_prefix']},")
    lines.extend(
        [
            "} as const;",
            "",
            "export type BinaryFrameName = keyof typeof BinaryPrefix;",
            "export type BinaryPrefixValue = (typeof BinaryPrefix)[BinaryFrameName];",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--schema", type=Path, default=DEFAULT_SCHEMA)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    generated = generate(args.schema)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
